export const AuthoritiesConstant = {

  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_USER: 'ROLE_USER',
  HDFS_BROWSER: {
    HDFS_BROWSER_EXECUTE: 'HDFS_BROWSER.HDFS_BROWSER_EXECUTE',
    HDFS_BROWSER_READ: 'HDFS_BROWSER.HDFS_BROWSER_READ',
    HDFS_BROWSER_WRITE: 'HDFS_BROWSER.HDFS_BROWSER_WRITE',
  },
  DATALAKE_DASHBOARD: {
    DATALAKE_DASHBOARD_EXECUTE: 'DATALAKE_DASHBOARD.DATALAKE_DASHBOARD_EXECUTE',
    DATALAKE_DASHBOARD_READ: 'DATALAKE_DASHBOARD.DATALAKE_DASHBOARD_READ',
    DATALAKE_DASHBOARD_WRITE: 'DATALAKE_DASHBOARD.DATALAKE_DASHBOARD_WRITE',
  },
  APPLICATION_MANAGEMENT: {
    APPLICATION_MANAGEMENT_EXECUTE: 'APPLICATION_MANAGEMENT.APPLICATION_MANAGEMENT_EXECUTE',
    APPLICATION_MANAGEMENT_READ: 'APPLICATION_MANAGEMENT.APPLICATION_MANAGEMENT_READ',
    APPLICATION_MANAGEMENT_WRITE: 'APPLICATION_MANAGEMENT.APPLICATION_MANAGEMENT_WRITE',
  },
  INGESTION_MONITOR: {
    INGESTION_MONITOR_EXECUTE: 'INGESTION_MONITOR.INGESTION_MONITOR_EXECUTE',
    INGESTION_MONITOR_READ: 'INGESTION_MONITOR.INGESTION_MONITOR_READ',
    INGESTION_MONITOR_WRITE: 'INGESTION_MONITOR.INGESTION_MONITOR_WRITE'
  },
  INGESTION_FLOW_MANAGER: {
    INGESTION_FLOW_MANAGER_EXECUTE: 'INGESTION_FLOW_MANAGER.INGESTION_FLOW_MANAGER_EXECUTE',
    INGESTION_FLOW_MANAGER_READ: 'INGESTION_FLOW_MANAGER.INGESTION_FLOW_MANAGER_READ',
    INGESTION_FLOW_MANAGER_WRITE: 'INGESTION_FLOW_MANAGER.INGESTION_FLOW_MANAGER_WRITE'
  },
  ROLE_MANAGER: {
    ROLE_MANAGER_EXECUTE: 'ROLE_MANAGER.ROLE_MANAGER_EXECUTE',
    ROLE_MANAGER_READ: 'ROLE_MANAGER.ROLE_MANAGER_READ',
    ROLE_MANAGER_WRITE: 'ROLE_MANAGER.ROLE_MANAGER_WRITE'
  },
  USER_HDFS_MANAGER: {
    USER_HDFS_MANAGER_EXECUTE: 'USER_HDFS_MANAGER.USER_HDFS_MANAGER_EXECUTE',
    USER_HDFS_MANAGER_READ: 'USER_HDFS_MANAGER.USER_HDFS_MANAGER_READ',
    USER_HDFS_MANAGER_WRITE: 'USER_HDFS_MANAGER.USER_HDFS_MANAGER_WRITE'
  },
  USER_MANAGER: {
    USER_MANAGER_EXECUTE: 'USER_MANAGER.USER_MANAGER_EXECUTE',
    USER_MANAGER_READ: 'USER_MANAGER.USER_MANAGER_READ',
    USER_MANAGER_WRITE: 'USER_MANAGER.USER_MANAGER_WRITE'
  },
  CONNECTION_MANAGER: {
    CONNECTION_MANAGER_EXECUTE: 'CONNECTION_MANAGER.CONNECTION_MANAGER_EXECUTE',
    CONNECTION_MANAGER_READ: 'CONNECTION_MANAGER.CONNECTION_MANAGER_READ',
    CONNECTION_MANAGER_WRITE: 'CONNECTION_MANAGER.CONNECTION_MANAGER_WRITE'
  },
  MODULE_MANAGER: {
    MODULE_MANAGER_EXECUTE: 'MODULE_MANAGER.MODULE_MANAGER_EXECUTE',
    MODULE_MANAGER_READ: 'MODULE_MANAGER.MODULE_MANAGER_READ',
    MODULE_MANAGER_WRITE: 'MODULE_MANAGER.MODULE_MANAGER_WRITE'
  },
  SERVER_IP_MANAGER: {
    SERVER_IP_MANAGER_EXECUTE: 'SERVER_IP_MANAGER.SERVER_IP_MANAGER_EXECUTE',
    SERVER_IP_MANAGER_READ: 'SERVER_IP_MANAGER.SERVER_IP_MANAGER_READ',
    SERVER_IP_MANAGER_WRITE: 'SERVER_IP_MANAGER.SERVER_IP_MANAGER_WRITE'
  },
  EDIT_IP_TABLE: {
    EDIT_IP_TABLE_EXECUTE: 'EDIT_IP_TABLE.EDIT_IP_TABLE_EXECUTE',
    EDIT_IP_TABLE_READ: 'EDIT_IP_TABLE.EDIT_IP_TABLE_READ',
    EDIT_IP_TABLE_WRITE: 'EDIT_IP_TABLE.EDIT_IP_TABLE_WRITE'
  },
  GROUP_CHART: {
    GROUP_CHART_WRITE: 'GROUP_CHART.GROUP_CHART_WRITE',
    GROUP_CHART_EXECUTE: 'GROUP_CHART.GROUP_CHART_EXECUTE',
    GROUP_CHART_READ: 'GROUP_CHART.GROUP_CHART_READ'
  },
  JOB_MANAGEMENT: {
    JOB_MANAGEMENT_EXECUTE: 'JOB_MANAGEMENT.JOB_MANAGEMENT_EXECUTE',
    JOB_MANAGEMENT_WRITE: 'JOB_MANAGEMENT.JOB_MANAGEMENT_WRITE',
    JOB_MANAGEMENT_READ: 'JOB_MANAGEMENT.JOB_MANAGEMENT_READ',
  },
  DATA_LAKE: {
    DATALAKE_EXECUTE: 'DATA_LAKE.DATALAKE_EXECUTE',
    DATALAKE_WRITE: 'DATA_LAKE.DATALAKE_WRITE',
    DATALAKE_READ: 'DATA_LAKE.DATALAKE_READ',
  },
  DB_MAKE_FILE_CONFIG: {
    DB_MAKE_FILE_CONFIG_WRITE: 'DB_MAKE_FILE_CONFIG.DB_MAKE_FILE_CONFIG_WRITE',
    DB_MAKE_FILE_CONFIG_READ: 'DB_MAKE_FILE_CONFIG.DB_MAKE_FILE_CONFIG_READ',
    DB_MAKE_FILE_CONFIG_EXECUTE: 'DB_MAKE_FILE_CONFIG.DB_MAKE_FILE_CONFIG_EXECUTE',
  },
  ACCESS_MANAGEMENT: {
    ACCESS_MANAGEMENT_WRITE: 'ACCESS_MANAGEMENT.ACCESS_MANAGEMENT_WRITE',
    ACCESS_MANAGEMENT_READ: 'ACCESS_MANAGEMENT.ACCESS_MANAGEMENT_READ',
    ACCESS_MANAGEMENT_EXECUTE: 'ACCESS_MANAGEMENT.ACCESS_MANAGEMENT_EXECUTE',
  },
  ENCODE_TOOL: {
    ENCODE_TOOL_EXECUTE: 'ENCODE_TOOL.ENCODE_TOOL_EXECUTE',
    ENCODE_TOOL_READ: 'ENCODE_TOOL.ENCODE_TOOL_READ',
    ENCODE_TOOL_WRITE: 'ENCODE_TOOL.ENCODE_TOOL_WRITE',
  },
  EXPORT_FILE: {
    EXPORT_FILE_WRITE: 'EXPORT_FILE.EXPORT_FILE_WRITE',
    EXPORT_FILE_READ: 'EXPORT_FILE.EXPORT_FILE_READ',
    EXPORT_FILE_EXECUTE: 'EXPORT_FILE.EXPORT_FILE_EXECUTE',
  },
  ATLAS_UPDATE: {
    ATLAS_UPDATE_WRITE: 'ATLAS_UPDATE.ATLAS_UPDATE_WRITE',
    ATLAS_UPDATE_READ: 'ATLAS_UPDATE.ATLAS_UPDATE_READ',
    ATLAS_UPDATE_EXECUTE: 'ATLAS_UPDATE.ATLAS_UPDATE_EXECUTE',
  },
  ALERT_CONFIG: {
    ALERT_CONFIG_WRITE: 'ALERT_CONFIG.ALERT_CONFIG_WRITE',
    ALERT_CONFIG_READ: 'ALERT_CONFIG.ALERT_CONFIG_READ',
    ALERT_CONFIG_EXECUTE: 'ALERT_CONFIG.ALERT_CONFIG_EXECUTE',
  },
  DASHBOARD: {
    DASHBOARD_WRITE: 'DASHBOARD.DASHBOARD_WRITE',
    DASHBOARD_READ: 'DASHBOARD.DASHBOARD_READ',
    DASHBOARD_EXECUTE: 'DASHBOARD.DASHBOARD_EXECUTE',
  },
  SMS_ALERT_CONFIG: {
    SMS_ALERT_CONFIG_WRITE: 'SMS_ALERT_CONFIG.SMS_ALERT_CONFIG_WRITE',
    SMS_ALERT_CONFIG_READ: 'SMS_ALERT_CONFIG.SMS_ALERT_CONFIG_READ',
    SMS_ALERT_CONFIG_EXECUTE: 'SMS_ALERT_CONFIG.SMS_ALERT_CONFIG_EXECUTE',
  },
  UPLOAD_FILE: {
    UPLOAD_FILE_WRITE: 'UPLOAD_FILE.UPLOAD_FILE_WRITE',
    UPLOAD_FILE_READ: 'UPLOAD_FILE.UPLOAD_FILE_READ',
    UPLOAD_FILE_EXECUTE: 'UPLOAD_FILE.UPLOAD_FILE_EXECUTE',
  },
  LB_CONNECTION: {
    LB_CONNECTION_WRITE: 'LB_CONNECTION.LB_CONNECTION_WRITE',
    LB_CONNECTION_READ: 'LB_CONNECTION.LB_CONNECTION_READ',
    LB_CONNECTION_EXECUTE: 'LB_CONNECTION.LB_CONNECTION_EXECUTE',
  },
  ACCESS_AUTHORIZATION: {
    ACCESS_AUTHORIZATION_WRITE: 'ACCESS_AUTHORIZATION.ACCESS_AUTHORIZATION_WRITE',
    ACCESS_AUTHORIZATION_READ: 'ACCESS_AUTHORIZATION.ACCESS_AUTHORIZATION_READ',
    ACCESS_AUTHORIZATION_EXECUTE: 'ACCESS_AUTHORIZATION.ACCESS_AUTHORIZATION_EXECUTE',
  },
  THRIFT_MANAGE: {
    THRIFT_MANAGE_WRITE: 'THRIFT_MANAGE.THRIFT_MANAGE_WRITE',
    THRIFT_MANAGE_READ: 'THRIFT_MANAGE.THRIFT_MANAGE_READ',
    THRIFT_MANAGE_EXECUTE: 'THRIFT_MANAGE.THRIFT_MANAGE_EXECUTE',
  },
  ACCESS_LOG: {
    ACCESS_LOG_WRITE: 'ACCESS_LOG.ACCESS_LOG_WRITE',
    ACCESS_LOG_READ: 'ACCESS_LOG.ACCESS_LOG_READ',
    ACCESS_LOG_EXECUTE: 'ACCESS_LOG.ACCESS_LOG_EXECUTE',
  },
  DB_ORACLE_MANAGER: {
    DB_ORACLE_MANAGER_WRITE: 'DB_ORACLE_MANAGER.DB_ORACLE_MANAGER_WRITE',
    DB_ORACLE_MANAGER_READ: 'DB_ORACLE_MANAGER.DB_ORACLE_MANAGER_READ',
    DB_ORACLE_MANAGER_EXECUTE: 'DB_ORACLE_MANAGER.DB_ORACLE_MANAGER_EXECUTE',
  },
  LOOKUP_TABLE: {
    LOOKUP_TABLE_WRITE: 'LOOKUP_TABLE.LOOKUP_TABLE_WRITE',
    LOOKUP_TABLE_READ: 'LOOKUP_TABLE.LOOKUP_TABLE_READ',
    LOOKUP_TABLE_EXECUTE: 'LOOKUP_TABLE.LOOKUP_TABLE_EXECUTE',
  },
  IPTABLE_RULE: {
    IPTABLE_RULE_WRITE: 'IPTABLE_RULE.IPTABLE_RULE_WRITE',
    IPTABLE_RULE_READ: 'IPTABLE_RULE.IPTABLE_RULE_READ',
    IPTABLE_RULE_EXECUTE: 'IPTABLE_RULE.IPTABLE_RULE_EXECUTE',
  },
  FLOW_CUSTOMIZED: {
    FLOW_CUSTOMIZED_WRITE: 'FLOW_CUSTOMIZED.FLOW_CUSTOMIZED_WRITE',
    FLOW_CUSTOMIZED_READ: 'FLOW_CUSTOMIZED.FLOW_CUSTOMIZED_READ',
    FLOW_CUSTOMIZED_EXECUTE: 'FLOW_CUSTOMIZED.FLOW_CUSTOMIZED_EXECUTE',
  },
  RP_APP: {
    RP_APP_EXECUTE: 'RP_APP.RP_APP_EXECUTE',
    RP_APP_READ: 'RP_APP.RP_APP_READ',
    RP_APP_WRITE: 'RP_APP.RP_APP_WRITE',
  },
  SUPPORT_REQUEST: {
    SUPPORT_REQUEST_EXECUTE: 'SUPPORT_REQUEST.SUPPORT_REQUEST_EXECUTE',
    SUPPORT_REQUEST_READ: 'SUPPORT_REQUEST.SUPPORT_REQUEST_READ',
    SUPPORT_REQUEST_WRITE: 'SUPPORT_REQUEST.SUPPORT_REQUEST_WRITE',
  }
};
